# Generated by Django 3.1.3 on 2021-05-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=12)),
                ('quantity', models.IntegerField()),
                ('user', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=50)),
                ('img_url', models.URLField(max_length=300)),
                ('brand_name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
    ]
