# Generated by Django 3.1.3 on 2021-05-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_entry',
            name='img_url',
            field=models.URLField(max_length=301),
        ),
    ]
