# Generated by Django 3.1.3 on 2021-05-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210522_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_entry',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
