# Generated by Django 3.1.3 on 2021-05-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_product_entry_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_entry',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
