# Generated by Django 3.1.3 on 2021-05-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('product_id', models.CharField(default=0, max_length=100)),
                ('brand_name', models.CharField(max_length=30)),
                ('img_url', models.URLField(max_length=300)),
                ('price', models.IntegerField()),
                ('avl_quantity', models.IntegerField(default=0)),
                ('specs', models.CharField(max_length=500)),
            ],
        ),
    ]
